export const startupsPlans = [
  {
    name: "Free Forever Plan",
    price: "₹0",
    period: "/Year",
    description: "Ignite Your Idea!",
    features: [
      "🏢 Basic AI expertise resources",
      "🎟️ Basic Template website",
      "📧 1 Email ID",
      "💾 50 MB Data Storage",
      "🛡️ Basic Firewall",
      "📚 Online Resources Support"
    ],
    cta: "Choose Free Forever Plan",
    popular: false,
    gradient: "green",
    specialOffer: "FREE FOREVER"
  },
  {
    name: "Beginner",
    price: "₹16000",
    period: "/Year",
    description: "Ignite Your Idea!",
    features: [
      "🏢 Basic Virtual Space",
      "🎟️ 1 Participation Credit",
      "🤖 1 Basic AI Assistant",
      "🌐 Basic Template Website",
      "📧 1 Email ID",
      "📊 Basic Contact Management",
      "💾 100 MB Data Storage",
      "🛡️ Basic Firewall",
      "📚 Online Resources Support",
      "Customer Support: Online Resources",
      "📚 Training and Onboarding: Online Resources"
    ],
    cta: "Choose Beginner Plan",
    popular: false,
    gradient: "green",
    specialOffer: "STARTUP STARTER"
  },
  {
    name: "Basic",
    price: "₹24000",
    period: "/Year",
    description: "Nurture Your Vision!",
    features: [
      "🏢 Customizable Virtual Office",
      "🎟️ 5 Participation Credits",
      "🤖 1 Advanced AI Assistant",
      "🌐 Customizable Template Website",
      "📧 5 Email IDs",
      "📊 Lead Management, Sales Pipeline",
      "💾 1 GB Data Storage",
      "🛡️ Advanced Firewall, Encryption",
      "📚 Email Support",
      "👩‍🏫 Personalized Onboarding, Online Resources",
      "🌐 Access to Online Community",
      "🎁 I2u.ai Points: 100",
      "🤖 AI-powered Chatbot"
    ],
    cta: "Choose Basic Plan",
    popular: true,
    gradient: "blue",
    specialOffer: "VISION BUILDER"
  },
  {
    name: "Advanced",
    price: "₹36000",
    period: "/Year",
    description: "Accelerate Your Growth!",
    features: [
      "🏢 Advanced Virtual Office with AI Assistant",
      "🎟️ 10 Participation Credits",
      "🤖 2 Advanced AI Assistants",
      "🌐 Custom Design with E-commerce",
      "📧 10 Email IDs",
      "📊 Marketing Automation, Customer Support",
      "💾 5 GB Data Storage",
      "🛡️ AI-powered Threat Detection",
      "📚 AI Agent Phone Support",
      "📅 Quarterly AI Powered Training Sessions",
      "🌐 Access to Exclusive Online Events, Community",
      "🎁 I2u.ai Points: 500",
      "📝 AI-powered Content Generation, Marketing Automation"
    ],
    cta: "Choose Advanced Plan",
    popular: false,
    gradient: "pink",
    specialOffer: "GROWTH ACCELERATOR"
  },
  {
    name: "Professional",
    price: "₹60000",
    period: "/Year",
    description: "Connect with Unicorns!",
    features: [
      "🏢 Premium Virtual Office with Virtual Reality",
      "🎟️ 20 Participation Credits",
      "🤖 3 High-end AI Assistants",
      "🌐 Custom Design with AI-powered Content Generation",
      "📧 20 Email IDs",
      "📊 AI-powered Sales Forecasting",
      "💾 10 GB Data Storage",
      "🛡️ AI-powered Incident Response",
      "📚 Priority AI Agent Phone Support",
      "📊 Monthly AI Powered Progress Review",
      "🌐 Access to Online VIP Events, Community",
      "🦄 Dedicated Unicorn Coach, Accelerated Growth Plan",
      "🎁 I2u.ai Points: 1,000",
      "🔮 AI-powered Predictive Analytics, Customer Segmentation"
    ],
    cta: "Choose Professional Plan",
    popular: false,
    gradient: "blue",
    specialOffer: "UNICORN CONNECTOR"
  },
  {
    name: "Pro Max Ultra",
    price: "₹100000",
    period: "/Year",
    description: "Create Your Legacy!",
    features: [
      "🏢 Ultra-Premium Virtual Office with AI-powered Decor",
      "🎟️ 50 Participation Credits",
      "🤖 5 Top-notch AI Assistants",
      "🌐 Custom Design with AI-powered Content Generation and Virtual Reality",
      "📧 50 Email IDs",
      "📊 AI-powered Predictive Maintenance",
      "💾 50 GB Data Storage",
      "🛡️ Top Notch AI-powered Security",
      "📚 Dedicated 24/7 AI Support",
      "🎓 Comprehensive AI Powered Onboarding, Ongoing Training, and Coaching",
      "🌐 Access to Online Ultra-Exclusive Events, AI Powered Networking",
      "🦄 AI Powered Unicorn Mentorship, Legacy Creation",
      "🎁 I2u.ai Points: 5,000",
      "📊 AI-powered Business Intelligence, AI-powered Predictive Maintenance"
    ],
    cta: "Choose Pro Max Ultra",
    popular: false,
    gradient: "pink",
    specialOffer: "LEGACY CREATOR"
  }
];
